name: push_notifications_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^13.2.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
